# Generated by Django 5.0.4 on 2024-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recetamedica",
            name="examenes",
        ),
        migrations.RemoveField(
            model_name="recetamedica",
            name="paciente",
        ),
        migrations.AddField(
            model_name="recetamedica",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ETS", "Chequeo de ETS"),
                    ("Embarazo", "Chequeo de Embarazo"),
                    ("Examenes", "Examenes"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recetamedica",
            name="descripcion",
            field=models.TextField(default="Por definir"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recetamedica",
            name="nombre",
            field=models.CharField(default="Por Definir", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recetamedica",
            name="fecha_emision",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="recetamedica",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
